CREATE TYPE products_status AS ENUM (
    'out_of_stock',
    'in_stock',
    'running_low'
    );

CREATE TABLE merchants
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_name VARCHAR,
    phone         INT UNIQUE NOT NULL,
    password      VARCHAR    NOT NULL,
    created_at    TIMESTAMP,
    PRIMARY KEY (id, merchant_name)
);

CREATE TABLE buyers
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR,
    phone      INT UNIQUE NOT NULL,
    password   VARCHAR    NOT NULL,
    created_at TIMESTAMP DEFAULT (now())
);

CREATE TABLE order_items
(
    order_id   int,
    product_id int,
    quantity   int DEFAULT 1
);

CREATE TABLE orders
(
    id         INT PRIMARY KEY,
    buyer_id   INT UNIQUE NOT NULL,
    status     VARCHAR,
    created_at VARCHAR
);

CREATE TABLE products
(
    id          INT PRIMARY KEY,
    name        VARCHAR,
    merchant_id INT NOT NULL,
    price       INT,
    status      products_status,
    created_at  TIMESTAMP DEFAULT (now())
);

CREATE INDEX product_status ON products (merchant_id, status);

CREATE UNIQUE INDEX ON products (id);

ALTER TABLE order_items
    ADD FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items
    ADD FOREIGN KEY (product_id) REFERENCES products (id);
