CREATE TYPE "products_status" AS ENUM (
    'out_of_stock',
    'in_stock',
    'running_low'
    );

CREATE TABLE "merchants" (
                             "id"  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "phone" int UNIQUE,
                             "merchant_name" varchar,
                             "created_at" timestamp,
                             "admin_id" int,
                             PRIMARY KEY ("id", "merchant_name")
);

CREATE TABLE "buyers" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "full_name" varchar,
                          "phone" int UNIQUE,
                          "created_at" timestamp
);

CREATE TABLE "order_items" (
                               "order_id" int,
                               "product_id" int,
                               "quantity" int DEFAULT 1
);

CREATE TABLE "orders" (
                          "id" int PRIMARY KEY,
                          "buyer_id" int UNIQUE NOT NULL,
                          "status" varchar,
                          "created_at" varchar
);

CREATE TABLE "products" (
                            "id" int PRIMARY KEY,
                            "name" varchar,
                            "merchant_id" int NOT NULL,
                            "price" int,
                            "status" products_status,
                            "created_at" datetime DEFAULT (now())
);

CREATE INDEX "product_status" ON "products" ("merchant_id", "status");

CREATE UNIQUE INDEX ON "products" ("id");

ALTER TABLE "merchants" ADD FOREIGN KEY ("admin_id") REFERENCES "buyers" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");
